FrontEnd/MVC/Models/EditarObjetoViewModel.cs
using IESPeniasNegras.Ecotrans.Nucleo.Acciones.Objetos;
using IESPeniasNegras.Ecotrans.Nucleo.Model;

namespace IESPeniasNegras.Ecotrans.MVC.Models
{
    public class EditarObjetoViewModel : EditarObjetoRequest
    {
       public TipoObjeto TipoObjeto { get; set; }
       public IEnumerable<Estado> Estado { get; set; }

    }
}

FrontEnd/MVC/Models/ErrorViewModel.cs
namespace MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FrontEnd/MVC/Models/FormularioDonacionesViewModel.cs
using MVC.Models;
using System.Collections.Generic;
using IESPeniasNegras.Ecotrans.Nucleo.Acciones.Donacion;
using IESPeniasNegras.Ecotrans.Nucleo.Model;

namespace IESPeniasNegras.Ecotrans.MVC.Models
{
    public class FormularioDonacionesViewModel
    {
        public Donacion donacion {get; set;}

        public string Titulo => this.donacion.Id == 0 ? "Nueva Donación" : "Editar Donación";
    }
}

FrontEnd/MVC/Controllers/DireccionesController.cs
using IESPeniasNegras.Ecotrans.Nucleo.Acciones.Direcciones;
using Microsoft.AspNetCore.Mvc;


namespace MVC.Controllers
{
    public class DireccionesController: Controller
    {

        public AccionesDirecciones AccionesDireccion { get; set; }

        public DireccionesController(AccionesDirecciones AccionesDireccion)
        {
            this.AccionesDireccion = AccionesDireccion;
        }

        //[Authorize(Roles =NombreRol....)]
        public IActionResult Guardar(EditarDireccionRequest editarDireccionesRequest)
        {

            var respuesta = AccionesDireccion.Editar(editarDireccionesRequest);
            return View("Detalles", respuesta);

        }
        //[Authorize(Roles =NombreRol....)]
        public IActionResult Crear(CrearDireccionRequest crear)
        {
            return View("FormularioCrear",crear);
        }
    }
}

FrontEnd/MVC/Controllers/DonacionesController.cs
using IESPeniasNegras.Ecotrans.Nucleo.Acciones.Donacion;
using Microsoft.AspNetCore.Mvc;

namespace IESPeniasNegras.Ecotrans.MVC.Controllers
{
    public class DonacionesController : Controller
    {

        private readonly AccionesDonacion accionesDonacion;

        public DonacionesController(AccionesDonacion accionesDonacion)
        {
            this.accionesDonacion = accionesDonacion;
        }

        public IActionResult Index(string? buscar = null)
        {
            var elementos = accionesDonacion.Listar(new ListarDonacionRequest(buscar));
            return View(elementos);
        }
    }
}

FrontEnd/MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Models;
using System.Diagnostics;

namespace MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FrontEnd/MVC/Controllers/ObjetosController.cs
using IESPeniasNegras.Ecotrans.Nucleo.Acciones.Objetos;
using Microsoft.AspNetCore.Mvc;

namespace IESPeniasNegras.Ecotrans.MVC.Controllers;

public class ObjetosController : Controller
{

    private readonly AccionesObjeto accionesObjeto;

    public ObjetosController(AccionesObjeto accionesObjeto)
    {
        this.accionesObjeto = accionesObjeto;
    }


    public IActionResult Detalles(ListarObjetoElemento elemento)
    {
        return View(elemento);
    }

    public IActionResult Index(string? buscar = null)
    {
        var elementos = accionesObjeto.Listar(new ListarObjetoRequest(buscar));
        return View(elementos);
    }

    public IActionResult Editar(ListarObjetoElemento editar)
    {
        return View("FormularioEdicion", editar);
    }

    public IActionResult Guardar(EditarObjetoRequest editarObjetoRequest)
    {
        
        var respuesta = accionesObjeto.Editar (editarObjetoRequest);
        return View("Detalles", respuesta);
        
    }
}

FrontEnd/MVC/Controllers/UsuariosController.cs
using IESPeniasNegras.Ecotrans.Nucleo.Acciones.Usuarios;
using Microsoft.AspNetCore.Mvc;

namespace MVC.Controllers;


    public class UsuariosController : Controller
    {
        public AccionesUsuarios accionesUsuarios { get; set; }

        public UsuariosController(AccionesUsuarios AccionesDonacion)
        {
            this.accionesUsuarios = AccionesDonacion;
        }

         public IActionResult Index(string? buscar = null)
        {
            var elementos = accionesUsuarios.Listar(new ListarUsuarioRequest(buscar));
            return View(elementos);
        }
    }

FrontEnd/MVC/Views/Ciudades/Index.cshtml
@using IESPeniasNegras.Ecotrans.Nucleo.Acciones.Ciudades
@model  ListarCiudadResponse

<h2>Listado de Ciudades</h2>
@Html.ActionLink("Nueva Ciudad", "Nueva", "Ciudades", null, new { @class="btn btn-info" })
@if (Model.Elementos.Count == 0)
{
    <h3>UPPS .... Lo sentimos ,no hay ninguna ciudad  registrada</h3>
}
else
{
    <table class="table table-bordered table-hover">
       
    </table>
}

FrontEnd/MVC/Views/Direcciones/FormularioCrear.cshtml
@using IESPeniasNegras.Ecotrans.Nucleo.Acciones.Direcciones

@model CrearDireccionRequest;
@{
    ViewData["Title"] = "Formulario Direcciones";
}
@using (Html.BeginForm("Edit", "Direcciones"))
{
    <div class="form-group">
        @Html.LabelFor(d => d.ProvinciaId, "ProvinciaId")
        @Html.TextBoxFor(d => d.ProvinciaId, new { @class = "form-control"})
        @Html.ValidationMessageFor(d => d.ProvinciaId, "Este campo es requerido")
    </div>
    <div class="form-group">
        @Html.LabelFor(d => d.CiudadId, "Ciudad")
        @Html.TextBoxFor(d => d.CiudadId, new { @class="form-control md-6" } )
        @Html.ValidationMessageFor(d => d.CiudadId, "Este campo es requerido"  )
    </div>
    <div class="form-group">
        @Html.LabelFor(d => d.Direccion1, "Direccion1")
        @Html.TextBoxFor(d => d.Direccion1, new { @class="form-control md-6" } )
        @Html.ValidationMessageFor(d => d.Direccion1, "Este campo es requerido")
    </div>


    <div class="form-group">
        @Html.LabelFor(d => d.Direccion2, "Direccion2")
        @Html.TextBoxFor(d => d.Direccion2, new { @class="form-control md-6" } )
        @Html.ValidationMessageFor(d => d.Direccion2, "Este campo es opcional")
    </div>
   
    <div class="form-group">
        @Html.LabelFor(d => d.CodigoPostal, "CodigoPostal")
        @Html.TextBoxFor(d => d.CodigoPostal, new { @class="form-control md-6" } )
        @Html.ValidationMessageFor(d => d.CodigoPostal, "Este campo es requerido")
    </div>


}

FrontEnd/MVC/Views/Direcciones/Index.cshtml
@using IESPeniasNegras.Ecotrans.Nucleo.Acciones.Direcciones

@model CrearDireccionRequest;
@{
    ViewData["Title"] = "Formulario Direcciones";
}
@using (Html.BeginForm("Edit", "Direcciones"))
{
     @Html.HiddenFor(d => d.IdCrear)

    <div class="form-group">
        @Html.LabelFor(d => d.ProvinciaId, "ProvinciaId")
        @Html.TextBoxFor(d => d.ProvinciaId, new { @class = "form-control"})
        @Html.ValidationMessageFor(d => d.ProvinciaId, "Este campo es requerido")
    </div>
    <div class="form-group">
        @Html.LabelFor(d => d.CiudadId, "Ciudad")
        @Html.TextBoxFor(d => d.CiudadId, new { @class="form-control md-6" } )
        @Html.ValidationMessageFor(d => d.CiudadId, "Este campo es requerido"  )
    </div>
    <div class="form-group">
        @Html.LabelFor(d => d.Direccion1, "Direccion1")
        @Html.TextBoxFor(d => d.Direccion1, new { @class="form-control md-6" } )
        @Html.ValidationMessageFor(d => d.Direccion1, "Este campo es requerido")
    </div>


    <div class="form-group">
        @Html.LabelFor(d => d.Direccion2, "Direccion2")
        @Html.TextBoxFor(d => d.Direccion2, new { @class="form-control md-6" } )
        @Html.ValidationMessageFor(d => d.Direccion2, "Este campo es opcional")
    </div>
   
    <div class="form-group">
        @Html.LabelFor(d => d.CodigoPostal, "CodigoPostal")
        @Html.TextBoxFor(d => d.CodigoPostal, new { @class="form-control md-6" } )
        @Html.ValidationMessageFor(d => d.CodigoPostal, "Este campo es requerido")
    </div>


}

FrontEnd/MVC/Views/Donaciones/FormularioDonaciones.cshtml
@using IESPeniasNegras.Ecotrans.Nucleo.Acciones.Donacion
@model EditarDonacionRequest;
@{
    ViewData["Title"] = "Formulario Donaciones";
}
@using (Html.BeginForm("Edit", "Donaciones"))
{
     @Html.HiddenFor(d => d.IdEdicion)

    <div class="form-group">
        @Html.LabelFor(d => d.Titulo, "Título para la donación")
        @Html.TextBoxFor(d => d.Titulo, new { @class = "form-control"})
        @Html.ValidationMessageFor(d => d.Titulo, "Este campo es requerido")
    </div>
    <div class="form-group">
        @Html.LabelFor(d => d.FechaInicio, "Fecha de inicio")
        @Html.TextBoxFor(d => d.FechaInicio, new { @class="form-control md-6" } )
        @Html.ValidationMessageFor(d => d.FechaInicio)
    </div>
    <div class="form-group">
        @Html.LabelFor(d => d.FechaFin, "Fecha de fin")
        @Html.TextBoxFor(d => d.FechaFin, new { @class="form-control md-6" } )
        @Html.ValidationMessageFor(d => d.FechaFin)
    </div>
    <div class="form-group">
        @Html.LabelFor(d => d.Descripcion, "Descripción de la donación")
        @Html.TextBoxFor(d => d.Descripcion, new { @class = "form-control"})
        @Html.ValidationMessageFor(d => d.Descripcion)
    </div>
     <button type="submit" class="btn btn-primary">Guardar</button>
}

FrontEnd/MVC/Views/Donaciones/Index.cshtml
@using IESPeniasNegras.Ecotrans.Nucleo.Acciones.Donacion
@model  ListarDonacionResponse


<h2>Listado de Donaciones</h2>
@Html.ActionLink("Nueva Donacion", "Nuevo", "Donaciones", null, new { @class="btn btn-info" })

@if (Model.Elementos.Count == 0)
{
<h3>UPPS .... Lo sentimos ,no hay ninguna donacion  registrada</h3>
}

else
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Usuario</th>
                <th>Titulo</th>
                <th>Descripcion</th>
                <th>FechaInicio</th>
                <th>FechaFinal</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var donacion in Model.Elementos)
            {
                <tr>
                    <td>@donacion.Usuario</td>
                    <td>@Html.ActionLink(@donacion.Usuario, "Detalles", new {donacion= donacion.Usuario})</td>
                    <td>@donacion.Titulo</td>
                    <td>@donacion.Usuario</td>
                    <td>@donacion.Descripcion</td>
                    <td>@donacion.FechaInicio</td>
                    <td>@donacion.FechaFinal</td>
                </tr>
            }
        </tbody>
    </table>
}
                

FrontEnd/MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FrontEnd/MVC/Views/HomeController1/Index.cshtml
@using IESPeniasNegras.Ecotrans.Nucleo.Acciones.Direcciones
@using IESPeniasNegras.Ecotrans.Nucleo.Acciones.Donacion
@model EditarDireccionRequest;
@{
    ViewData["Title"] = "Formulario Direcciones";
}
@using (Html.BeginForm("Edit", "Direcciones"))
{
     @Html.HiddenFor(d => d.IdEdicion)

    <div class="form-group">
        @Html.LabelFor(d => d.ProvinciaId, "ProvinciaId")
        @Html.TextBoxFor(d => d.ProvinciaId, new { @class = "form-control"})
        @Html.ValidationMessageFor(d => d.ProvinciaId, "Este campo es requerido")
    </div>
    <div class="form-group">
        @Html.LabelFor(d => d.CiudadId, "Ciudad")
        @Html.TextBoxFor(d => d.CiudadId, new { @class="form-control md-6" } )
        @Html.ValidationMessageFor(d => d.CiudadId, "Este campo es requerido"  )
    </div>
    <div class="form-group">
        @Html.LabelFor(d => d.Direccion1, "Direccion1")
        @Html.TextBoxFor(d => d.Direccion1, new { @class="form-control md-6" } )
        @Html.ValidationMessageFor(d => d.Direccion1, "Este campo es requerido")
    </div>


    <div class="form-group">
        @Html.LabelFor(d => d.Direccion2, "Direccion2")
        @Html.TextBoxFor(d => d.Direccion2, new { @class="form-control md-6" } )
        @Html.ValidationMessageFor(d => d.Direccion2, "Este campo es opcional")
    </div>
   
    <div class="form-group">
        @Html.LabelFor(d => d.CodigoPostal, "CodigoPostal")
        @Html.TextBoxFor(d => d.CodigoPostal, new { @class="form-control md-6" } )
        @Html.ValidationMessageFor(d => d.CodigoPostal, "Este campo es requerido")
    </div>


}

FrontEnd/MVC/Views/Objetos/Detalles.cshtml
@using IESPeniasNegras.Ecotrans.Nucleo.Acciones.Objetos;
@model ListarObjetoElemento

@{
    ViewData["Title"] = "Detalles objeto";
}
<h1>Detalles objeto</h1>
    <table>
        <tr> Id
            <td>@Html.DisplayNameFor(m => m.Id)</td>
            <td>@Model.Id </td>

        </tr>
        <tr> Nombre
            <td>@Html.DisplayNameFor(m => m.Nombre)</td>
            <td>@Model.Nombre </td>

        </tr>
        <tr> TipoObjetoId
            <td>@Html.DisplayNameFor(m => m.TipoObjetoId)</td>
            <td>@Model.TipoObjetoId </td>

        </tr>
        <tr> Estado
            <td>@Html.DisplayNameFor(m => m.Estado)</td>
            <td>@Model.Estado </td>

        </tr>
        <tr> Altura
            <td>@Html.DisplayNameFor(m => m.Altura)</td>
            <td>@Model.Altura </td>

        </tr>
        <tr> Anchura
            <td>@Html.DisplayNameFor(m => m.Anchura)</td>
            <td>@Model.Anchura </td>

        </tr>
        <tr> Profundidad
            <td>@Html.DisplayNameFor(m => m.Profundidad)</td>
            <td>@Model.Profundidad </td>

        </tr>
        <tr> Peso
            <td>@Html.DisplayNameFor(m => m.Peso)</td>
            <td>@Model.Peso </td>

        </tr>
    </table>

FrontEnd/MVC/Views/Objetos/EditarObjetos.cshtml
@using IESPeniasNegras.Ecotrans.MVC.Models
@using IESPeniasNegras.Ecotrans.Nucleo.Model
@model EditarObjetoViewModel;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using (Html.BeginForm("Edit", "Objeto"))
{
     @Html.HiddenFor(o => o.IdEdicion)

    <div class="form-group">
        @Html.LabelFor(o => o.Nombre)
        @Html.TextBoxFor(o => o.Nombre, new { @class = "form-control"})
        @Html.ValidationMessageFor(o => o.Nombre, "Este campo es requerido")
    </div>

     <div class="form-group">
        @Html.LabelFor(o => o.TipoObjeto)
        @Html.DropDownListFor(o => o.TipoObjeto, new SelectList(Enum.GetValues(typeof(TipoObjeto))), "", new { @class = "form-control" })
        @Html.ValidationMessageFor(o => o.TipoObjeto)
    </div>

      <div class="form-group">
        @Html.LabelFor(o => o.Estado)
        @Html.DropDownListFor(o => o.Estado, new SelectList(Enum.GetValues(typeof(Estado))), "Selecciona el estado", new { @class = "form-control" })
        @Html.ValidationMessageFor(o => o.Estado)
    </div>

     <div class="form-group">
        @Html.LabelFor(m => m.Altura)
        @Html.TextBoxFor(m => m.Altura, new { @class = "form-control"})
        @Html.ValidationMessageFor(o => o.Altura)
    </div>

     <div class="form-group">
        @Html.LabelFor(m => m.Anchura)
        @Html.TextBoxFor(m => m.Anchura, new { @class = "form-control"})
        @Html.ValidationMessageFor(o => o.Anchura)
    </div>

     <div class="form-group">
        @Html.LabelFor(m => m.Profundidad)
        @Html.TextBoxFor(m => m.Profundidad, new { @class = "form-control"})
        @Html.ValidationMessageFor(o => o.Profundidad)
    </div>

     <div class="form-group">
        @Html.LabelFor(o => o.Peso)
        @Html.TextBoxFor(o => o.Peso, new { @class = "form-control"})
        @Html.ValidationMessageFor(o => o.Peso)
    </div>
}

FrontEnd/MVC/Views/Objetos/FormularioEdicion.cshtml
@using IESPeniasNegras.Ecotrans.MVC.Models
@using IESPeniasNegras.Ecotrans.Nucleo.Model
@model EditarObjetoViewModel;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using (Html.BeginForm("Edit", "Objeto"))
{
     @Html.HiddenFor(o => o.IdEdicion)

    <div class="form-group">
        @Html.LabelFor(o => o.Nombre)
        @Html.TextBoxFor(o => o.Nombre, new { @class = "form-control"})
        @Html.ValidationMessageFor(o => o.Nombre, "Este campo es requerido")
    </div>

     <div class="form-group">
        @Html.LabelFor(o => o.TipoObjeto)
        @Html.DropDownListFor(o => o.TipoObjeto, new SelectList(Enum.GetValues(typeof(TipoObjeto))), "", new { @class = "form-control" })
        @Html.ValidationMessageFor(o => o.TipoObjeto)
    </div>

      <div class="form-group">
        @Html.LabelFor(o => o.Estado)
        @Html.DropDownListFor(o => o.Estado, new SelectList(Enum.GetValues(typeof(Estado))), "Selecciona el estado", new { @class = "form-control" })
        @Html.ValidationMessageFor(o => o.Estado)
    </div>

     <div class="form-group">
        @Html.LabelFor(m => m.Altura)
        @Html.TextBoxFor(m => m.Altura, new { @class = "form-control"})
        @Html.ValidationMessageFor(o => o.Altura)
    </div>

     <div class="form-group">
        @Html.LabelFor(m => m.Anchura)
        @Html.TextBoxFor(m => m.Anchura, new { @class = "form-control"})
        @Html.ValidationMessageFor(o => o.Anchura)
    </div>

     <div class="form-group">
        @Html.LabelFor(m => m.Profundidad)
        @Html.TextBoxFor(m => m.Profundidad, new { @class = "form-control"})
        @Html.ValidationMessageFor(o => o.Profundidad)
    </div>

     <div class="form-group">
        @Html.LabelFor(o => o.Peso)
        @Html.TextBoxFor(o => o.Peso, new { @class = "form-control"})
        @Html.ValidationMessageFor(o => o.Peso)
    </div>
}

FrontEnd/MVC/Views/Objetos/index.cshtml
@using IESPeniasNegras.Ecotrans.Nucleo.Acciones.Objetos;
@model ListarObjetoResponse
@{
    ViewData["Title"] = "Listado de Objetos";
}

<table>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Estado</th>
            <th>Peso</th>
            <th>Dimensiones</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var objeto in Model.Elementos)
        {
            <tr>
                <td>@Html.ActionLink(@objeto.Nombre,"Detalles", new { id= objeto.Id})</td>
                <td>@objeto.Estado</td>
                <td>@objeto.Peso</td>
                <td>@objeto.GetDimensiones()</td>
            </tr>
        }
    </tbody>
</table>

FrontEnd/MVC/Views/Provincias/Index.cshtml
@using IESPeniasNegras.Ecotrans.Nucleo.Acciones.Provincias
@model  ListarProvinciaResponse

<h2>Listado de Provincias</h2>
@Html.ActionLink("Nueva Provincia", "Nueva", "Provincias", null, new { @class="btn btn-info" })
@if (Model.Elementos.Count == 0)
{
    <h3>UPPS .... Lo sentimos ,no hay ninguna provincia  registrada</h3>
}
else
{
    <table class="table table-bordered table-hover">
        
    </table>
}

FrontEnd/MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item nav-link text-dark">
                             @Html.ActionLink("Donaciones", "Index", "Donaciones", null, new { @class="nav-link text-dark" })
                        </li>
                        <li class="nav-item nav-link text-dark">
                            @Html.ActionLink("Objetos", "Index", "Objetos", null, new { @class="nav-link text-dark" })
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FrontEnd/MVC/Views/Usuarios/Index.cshtml
@using IESPeniasNegras.Ecotrans.Nucleo.Acciones.Usuarios
@model  ListarUsuarioResponse

<h2>Listado de Usuarios</h2>
@Html.ActionLink("Nuevo Usuario", "Nuevo", "Usuarios", null, new { @class="btn btn-info" })
@if (Model.Elementos.Count == 0)
{
    <h3>UPPS .... Lo sentimos, no encontramos ningún usuario  registrada</h3>
}
else
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Usuario</th>
                
            </tr>
        </thead>

        <tbody>
            <!---Tenemos el listado, los elementos pero no los enlaces--->

            @foreach(var usuario in Model.Elementos)
            {
                <tr>
                    <td>@usuario.Id</td>
                    <td>@Html.ActionLink(@usuario.Nombre, "Detalles", new {Id = usuario.Id})</td>

                </tr>
            }
        </tbody>
    </table>
}